-- View VW_ACTIVE_LECTURER_WORKLOAD
CREATE OR REPLACE VIEW INSTANCE.VW_ACTIVE_LECTURER_WORKLOAD AS
SELECT 
    -- Teacher details
    t.ID AS TEACHER_ID,
    t.NAME AS TEACHER_NAME,
    
    -- Workload calculation (sum of credited teacher hours)
    COALESCE(SUM(c.CREDITED_TEACHER_HOURS), 0) AS WORKLOAD
    
FROM 
    INSTANCE.LECTURER l
JOIN 
    INSTANCE.TEACHER t ON t.ID = l.TEACHER_ID
LEFT JOIN 
    INSTANCE.COURSE c ON c.TEACHER = t.ID
JOIN
    INSTANCE.SEARCH_CRITERIA sc ON sc.SEMESTER_START = c.COURSE_START
WHERE 
    l.IS_ACTIVE = TRUE
GROUP BY 
    t.ID, t.NAME;
--COMMENT ON VIEW INSTANCE.VW_ACTIVE_LECTURER_WORKLOAD IS 'The lecturer workload for the selected semester ("WS1516").';

-- View VW_ACTIVE_PROFESSOR_WORKLOAD
CREATE OR REPLACE VIEW INSTANCE.VW_ACTIVE_PROFESSOR_WORKLOAD AS
SELECT 
    -- Teacher details
    t.ID AS TEACHER_ID,
    t.NAME AS TEACHER_NAME,
    p.CREDIT_HOUR_ACCOUNT,
    
    -- Workload calculation (sum of credited teacher hours)
    COALESCE(SUM(c.CREDITED_TEACHER_HOURS), 0) AS WORKLOAD
    
FROM 
    INSTANCE.PROFESSOR p
JOIN 
    INSTANCE.TEACHER t ON t.ID = p.TEACHER_ID
LEFT JOIN 
    INSTANCE.COURSE c ON c.TEACHER = t.ID
JOIN
    INSTANCE.SEARCH_CRITERIA sc ON sc.SEMESTER_START = c.COURSE_START
WHERE 
    p.IS_ACTIVE = TRUE
GROUP BY 
    t.ID, t.NAME, p.CREDIT_HOUR_ACCOUNT;
--COMMENT ON VIEW INSTANCE.VW_ACTIVE_PROFESSOR_WORKLOAD IS 'The professor workload for the selected semester ("WS1516").';

-- View VW_OFFERED_COURSES
CREATE OR REPLACE VIEW INSTANCE.VW_OFFERED_COURSES AS
SELECT 
    -- Search Criteria
    sc.SEMESTER_START,
    
    -- Subject Details
    s.SUBJECT_NUMBER,
    s.SUBJECT_NAME,
    s.PLANNED_STUPO_HOURS,
    s.PLANNED_SCHEDULE_HOURS,
    s.SUBJECT_TYPE,

    -- Faculty
    t.FACULTY AS EXPORTING_FACULTY,
    s.FACULTY AS IMPORTING_FACULTY,
    
    -- Course Details
    c.ACTUAL_STUPO_HOURS,
    c.ACTUAL_SCHEDULE_HOURS,
    c.CREDITED_TEACHER_HOURS,
    
    -- Teacher Details from Course
    t.NAME AS TEACHER_NAME,
    
    -- Remarks
    s.REMARK AS SUBJECT_REMARK,
    t.REMARK AS TEACHER_REMARK

FROM 
    INSTANCE.SUBJECT s
LEFT JOIN 
    INSTANCE.COURSE c ON c.SUBJECT = s.SUBJECT_NUMBER 
JOIN
    INSTANCE.SEARCH_CRITERIA sc ON c.COURSE_START = sc.SEMESTER_START
LEFT JOIN 
    INSTANCE.TEACHER t ON t.ID = c.TEACHER;
--COMMENT ON VIEW INSTANCE.VW_OFFERED_COURSES IS 'All courses that are offered this semester ("WS1516")';

-- View offered Subjects
CREATE OR REPLACE VIEW INSTANCE.VW_OFFERED_SUBJECTS AS 
SELECT 
    --subject
    su.SUBJECT_NUMBER,
    su.SUBJECT_NAME,
    su.SUBJECT_TYPE,
    su.REMARK,
    su.PLANNED_STUPO_HOURS,
    su.PLANNED_SCHEDULE_HOURS

FROM INSTANCE.SUBJECT su;
--COMMENT ON VIEW INSTANCE.VW_OFFERED_SUBJECTS IS 'All subjects that currently exist in the database.
--Based on the "Subject Form" screenshot.';

-- View Professor_Function_Load
CREATE OR REPLACE VIEW INSTANCE.VW_PROFESSOR_FUNCTION_LOAD AS
SELECT 
    -- Teacher details
    t.NAME AS TEACHER_NAME,
    
    -- Function details
    f.NAME AS FUNCTION_NAME,
    f.FUNCTION_START,
    
    -- Workload (LOAD from FUNCTION_PROFESSOR table)
    f.LOAD AS FUNCTION_LOAD

FROM 
    INSTANCE.FUNCTION_PROFESSOR f
JOIN 
    INSTANCE.PROFESSOR p ON p.TEACHER_ID = f.PROFESSOR
JOIN 
    INSTANCE.TEACHER t ON t.ID = p.TEACHER_ID
JOIN 
    INSTANCE.SEARCH_CRITERIA sc ON f.FUNCTION_START = sc.SEMESTER_START
WHERE 
    p.IS_ACTIVE = TRUE;
--COMMENT ON VIEW INSTANCE.VW_PROFESSOR_FUNCTION_LOAD IS 'The professor function load for the selected semester ("WS1516").
--Based on the "Teaching Load Reduction - Input Form" screenshot.';

-- View Selected Courses Details
CREATE OR REPLACE VIEW INSTANCE.VW_SELECTED_COURSE_DETAILS AS
SELECT 
    -- Search Criteria
    sc.MAJOR,
    sc.SEMESTER,
    sc.SEMESTER_START,
    
    -- Subject Details
    s.SUBJECT_NUMBER,
    s.SUBJECT_NAME,
    s.PLANNED_STUPO_HOURS,
    s.PLANNED_SCHEDULE_HOURS,
    s.SUBJECT_TYPE,

    -- Faculty
    t.FACULTY AS EXPORTING_FACULTY,
    s.FACULTY AS IMPORTING_FACULTY,
    
    -- Course Details
    c.ACTUAL_STUPO_HOURS,
    c.ACTUAL_SCHEDULE_HOURS,
    c.CREDITED_TEACHER_HOURS,
    
    -- Teacher Details from Course
    t.NAME AS TEACHER_NAME,
    
    -- Remarks
    s.REMARK AS SUBJECT_REMARK,
    t.REMARK AS TEACHER_REMARK

FROM 
    INSTANCE.SEARCH_CRITERIA sc
JOIN 
    INSTANCE.SUBJECT s ON s.MAJOR = sc.MAJOR AND s.SEMESTER = sc.SEMESTER
LEFT JOIN 
    INSTANCE.COURSE c ON c.SUBJECT = s.SUBJECT_NUMBER AND c.COURSE_START = sc.SEMESTER_START
LEFT JOIN 
    INSTANCE.TEACHER t ON t.ID = c.TEACHER;
--COMMENT ON VIEW INSTANCE.VW_SELECTED_COURSE_DETAILS IS 'All courses for the currently selected search critera.
--Based on the "Planning - Input Form" screenshot.';

-- View Selece Service Details
CREATE OR REPLACE VIEW INSTANCE.VW_SELECTED_SERVICE_DETAILS AS
SELECT 
    -- Search Criteria
    sc.SEMESTER_START,
    
    -- Subject Details
    s.SUBJECT_NUMBER,
    s.SUBJECT_NAME,
    s.PLANNED_STUPO_HOURS,
    s.PLANNED_SCHEDULE_HOURS,
    s.SUBJECT_TYPE,

    -- Faculty
    t.FACULTY AS EXPORTING_FACULTY,
    s.FACULTY AS IMPORTING_FACULTY,
    
    -- Course Details
    c.ACTUAL_STUPO_HOURS,
    c.ACTUAL_SCHEDULE_HOURS,
    c.CREDITED_TEACHER_HOURS,
    
    -- Teacher Details from Course
    t.NAME AS TEACHER_NAME,
    
    -- Remarks
    s.REMARK AS SUBJECT_REMARK,
    t.REMARK AS TEACHER_REMARK

FROM 
    INSTANCE.SUBJECT s
LEFT JOIN 
    INSTANCE.COURSE c ON c.SUBJECT = s.SUBJECT_NUMBER 
JOIN
    INSTANCE.SEARCH_CRITERIA sc ON c.COURSE_START = sc.SEMESTER_START
LEFT JOIN 
    INSTANCE.TEACHER t ON t.ID = c.TEACHER
WHERE t.FACULTY != s.FACULTY;
--COMMENT ON VIEW INSTANCE.VW_SELECTED_SERVICE_DETAILS IS 'All services for the currently selected search critera.
--Based on the "Service" screenshot.';

-- View Selected Subject Details
CREATE OR REPLACE VIEW INSTANCE.VW_SELECTED_SUBJECT_DETAILS AS 
SELECT 
    --subject
    su.SUBJECT_NUMBER,
    su.SUBJECT_NAME,
    su.SUBJECT_TYPE,
    su.PLANNED_STUPO_HOURS,
    su.PLANNED_SCHEDULE_HOURS,
    su.SEMESTER,
    su.MAJOR AS SUBJECT_MAJOR,
    su.FACULTY AS SUBJECT_FACULTY,
    su.REMARK,
    --faculty
    fa.NAME AS FACULTY_NAME,
    --major
    ma.NAME AS MAJOR_NAME
  FROM INSTANCE.SUBJECT su
INNER JOIN 
    INSTANCE.FACULTY fa ON fa.ABBREVIATION = su.FACULTY
INNER JOIN
    INSTANCE.MAJOR ma ON ma.ABBREVIATION = su.MAJOR
INNER JOIN
    INSTANCE.SEARCH_CRITERIA sc ON sc.MAJOR = su.MAJOR  -- Join mit SEARCH_CRITERIA;
--COMMENT ON VIEW INSTANCE.VW_SELECTED_SUBJECT_DETAILS IS 'All subjects for the currently selected search criteria.';